
### Environment variables - Make sure you have http-client.env.json file with these variables
GET {{url}}/auth/test

### Register new user
POST {{url}}/auth/register
Content-Type: application/json

{
  "email": "test@test.dk",
  "name": "Test User",
  "password": "test123"

}

> {% client.global.set("auth_token", response.body.token); %}

### Login user
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "test@test.dk",
  "password": "test123"
}

> {% client.global.set("auth_token", response.body.token); %}

### Test protected user endpoint
GET {{url}}/protected/user_demo
Authorization: Bearer {{auth_token}}

### Add admin role
POST {{url}}/auth/user/addrole
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "role": "ADMIN"
}

### Test protected admin endpoint
GET {{url}}/protected/admin_demo
Authorization: Bearer {{auth_token}}

### Salling API Endpoints ###

### Sync all stores
POST {{url}}/stores/sync
Accept: application/json

### Get all stores
GET {{url}}/stores
Accept: application/json

### Get specific store
GET {{url}}/stores/1
Accept: application/json

### Sync products for specific store
POST {{url}}/stores/1/sync-products
Accept: application/json

### Get products for specific store
GET {{url}}/stores/1/products
Accept: application/json


### Sync all stores
POST http://localhost:7070/api/stores/sync
Accept: application/json

### Check result
GET http://localhost:7070/api/stores
Accept: application/json

